create table appointments (id integer not null auto_increment, a_date date not null, notes varchar(255), a_time time not null, total float(23), employee_id integer not null, patient_id integer not null, service_id integer not null, primary key (id)) engine=InnoDB;
create table patients (id integer not null auto_increment, address varchar(255) not null, date_of_birth date not null, email varchar(255) not null, patient_name varchar(255) not null, phone_number varchar(255) not null, primary key (id)) engine=InnoDB;
create table services (id integer not null auto_increment, duration integer not null, min_price integer not null, service_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table statuses (id integer not null auto_increment, status_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (id integer not null auto_increment, email varchar(255) not null, username varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (user_id integer not null, role varchar(255) not null) engine=InnoDB;
alter table patients add constraint UK_a370hmxgv0l5c9panryr1ji7d unique (email);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table appointments add constraint FK11meukil4sxene75mt05cb6uv foreign key (employee_id) references users (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table appointments add constraint FK5iltr7k9pows18hk8nc101vc1 foreign key (service_id) references services (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
